org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true

org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true

octant.platforms=false

octant.platforms.forge1211=false
